# Generated by Django 3.2.23 on 2023-11-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='booked',
            field=models.BooleanField(default=False, verbose_name='Booked'),
        ),
    ]
