# Generated by Django 3.2.23 on 2023-11-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apartments2',
        ),
    ]
