# Generated by Django 3.2.23 on 2023-11-22 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('rental_app', '0003_auto_20231122_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateTimeField(verbose_name='Date Booked')),
                ('room', models.ForeignKey(on_delete=models.SET('Room was removed/deleted'), to='rental_app.rooms', verbose_name='Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.prospectivetenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Booking History',
                'verbose_name_plural': 'Booking Histories',
                'ordering': ['-date_booked'],
                'get_latest_by': 'date_booked',
            },
        ),
    ]
