# Generated by Django 3.2.23 on 2023-11-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0004_booking_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking_history',
            options={'verbose_name': 'Booking History', 'verbose_name_plural': 'Booking Histories'},
        ),
        migrations.RemoveField(
            model_name='booking_history',
            name='date_booked',
        ),
    ]
