# Generated by Django 3.2.23 on 2023-11-22 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0005_auto_20231122_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking_history',
            options={'get_latest_by': 'date_booked', 'ordering': ['-date_booked'], 'verbose_name': 'Booking History', 'verbose_name_plural': 'Booking Histories'},
        ),
        migrations.AddField(
            model_name='booking_history',
            name='date_booked',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Booked'),
            preserve_default=False,
        ),
    ]
