# Generated by Django 3.2.23 on 2023-11-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0006_auto_20231122_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_history',
            name='date_booked',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Booked'),
        ),
    ]
