# Generated by Django 3.2.23 on 2023-11-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0007_alter_booking_history_date_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_history',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Room was removed/deleted'), to='rental_app.rooms', verbose_name='Room'),
        ),
    ]
