# Generated by Django 3.2.23 on 2023-11-22 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0008_alter_booking_history_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_history',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental_app.rooms', verbose_name='Room'),
        ),
    ]
