# Generated by Django 3.2.23 on 2023-11-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0009_alter_booking_history_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Page Type')),
                ('details', models.TextField(verbose_name='Page Detail')),
            ],
        ),
    ]
