# Generated by Django 3.2.23 on 2023-11-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0010_page'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rooms',
            unique_together={('room_number', 'apartment')},
        ),
    ]
