# Generated by Django 3.2.23 on 2023-11-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0011_alter_rooms_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='rent',
            field=models.PositiveIntegerField(default=0, verbose_name='Rent Charged'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('Single room', 'Single room'), ('Bedsitter', 'Bedsitter'), ('Studio', 'Studio'), ('Go Down', 'Go Down'), ('One-Bedroom', 'One-Bedroom'), ('Two-Bedroom', 'Two-Bedroom'), ('Three-Bedroom', 'Three-Bedroom'), ('Four-Bedroom', 'Four-Bedroom'), ('Shared room', 'Shared room'), ('En suite room', 'En suite room'), ('Self-contained apartment', 'Self-contained apartment'), ('Other', 'Other')], max_length=40, verbose_name='Room Type'),
        ),
    ]
