# Generated by Django 3.2.23 on 2023-12-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0012_auto_20231124_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=250, verbose_name='The actual link')),
                ('icon', models.CharField(max_length=10, verbose_name='Icon')),
            ],
        ),
    ]
