# Generated by Django 4.1.13 on 2024-01-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0013_social_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=500, verbose_name='Room Type')),
            ],
        ),
        migrations.AlterModelOptions(
            name='booking_history',
            options={'verbose_name': 'Booking History', 'verbose_name_plural': 'Booking Histories'},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name': 'room', 'verbose_name_plural': 'rooms'},
        ),
    ]
