# Generated by Django 4.1.13 on 2024-01-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0014_roomtype_alter_booking_history_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking_history',
            options={'get_latest_by': 'date_booked', 'verbose_name': 'Booking History', 'verbose_name_plural': 'Booking Histories'},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'get_latest_by': 'date_updated', 'verbose_name': 'room', 'verbose_name_plural': 'rooms'},
        ),
    ]
