# Generated by Django 4.1.13 on 2024-01-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0016_alter_roomtype_options_remove_rooms_room_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='type',
            new_name='room_type',
        ),
    ]
